language: java
jdk:
  - oraclejdk8
  - oraclejdk7
before_install:
  - pip install --user codecov
after_success:
  # Coveralls
  - mvn clean test jacoco:report coveralls:report
  # Codecov
  - codecov
